<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class DayResult extends Model
{
  use HasFactory;

  protected $fillable = [
    'day_id',
    'execution_scope',
    'result',
    'desires',
    'reluctance',
    'interference',
    'rejoice',
  ];

  public $timestamps = false;

//  protected static function boot()
//  {
//    parent::boot(); // TODO: Change the autogenerated stub
//
//    static::saved(function ($dayResult) {
//      $dayResult->student->update(['last_active_at' => now()]);
//    });
//  }

  public function student(): BelongsTo
  {
    return $this->belongsTo(Student::class);
  }

  public function day(): BelongsTo
  {
    return $this->belongsTo(Day::class);
  }
}
